/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetRouteImport } from './routes/auth_.reset'
import { Route as AuthForgotRouteImport } from './routes/auth_.forgot'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedWorkerIndexRouteImport } from './routes/_authenticated/worker/index'
import { Route as AuthenticatedCustomerIndexRouteImport } from './routes/_authenticated/customer/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminTroublesRouteImport } from './routes/_authenticated/admin/troubles'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicHooksTestCleanupRouteImport } from './routes/api/public/hooks/test-cleanup'
import { Route as ApiPublicHooksPushDispatchRouteImport } from './routes/api/public/hooks/push-dispatch'
import { Route as ApiPublicHooksAutoForceCompleteAbandonedRouteImport } from './routes/api/public/hooks/auto-force-complete-abandoned'
import { Route as ApiPublicHooksAutoConfirmCompletionRouteImport } from './routes/api/public/hooks/auto-confirm-completion'
import { Route as ApiPublicHooksAutoCancelOverdueRouteImport } from './routes/api/public/hooks/auto-cancel-overdue'
import { Route as ApiPublicConnectOnboardingRouteImport } from './routes/api/public/connect/onboarding'
import { Route as AuthenticatedWorkerJobIdRouteImport } from './routes/_authenticated/worker/job/$id'
import { Route as AuthenticatedCustomerRequestIdRouteImport } from './routes/_authenticated/customer/request/$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth_/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth_/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkerIndexRoute =
  AuthenticatedWorkerIndexRouteImport.update({
    id: '/worker/',
    path: '/worker/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomerIndexRoute =
  AuthenticatedCustomerIndexRouteImport.update({
    id: '/customer/',
    path: '/customer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTroublesRoute =
  AuthenticatedAdminTroublesRouteImport.update({
    id: '/admin/troubles',
    path: '/admin/troubles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTestCleanupRoute =
  ApiPublicHooksTestCleanupRouteImport.update({
    id: '/api/public/hooks/test-cleanup',
    path: '/api/public/hooks/test-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPushDispatchRoute =
  ApiPublicHooksPushDispatchRouteImport.update({
    id: '/api/public/hooks/push-dispatch',
    path: '/api/public/hooks/push-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoForceCompleteAbandonedRoute =
  ApiPublicHooksAutoForceCompleteAbandonedRouteImport.update({
    id: '/api/public/hooks/auto-force-complete-abandoned',
    path: '/api/public/hooks/auto-force-complete-abandoned',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoConfirmCompletionRoute =
  ApiPublicHooksAutoConfirmCompletionRouteImport.update({
    id: '/api/public/hooks/auto-confirm-completion',
    path: '/api/public/hooks/auto-confirm-completion',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoCancelOverdueRoute =
  ApiPublicHooksAutoCancelOverdueRouteImport.update({
    id: '/api/public/hooks/auto-cancel-overdue',
    path: '/api/public/hooks/auto-cancel-overdue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConnectOnboardingRoute =
  ApiPublicConnectOnboardingRouteImport.update({
    id: '/api/public/connect/onboarding',
    path: '/api/public/connect/onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedWorkerJobIdRoute =
  AuthenticatedWorkerJobIdRouteImport.update({
    id: '/worker/job/$id',
    path: '/worker/job/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomerRequestIdRoute =
  AuthenticatedCustomerRequestIdRouteImport.update({
    id: '/customer/request/$id',
    path: '/customer/request/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/troubles': typeof AuthenticatedAdminTroublesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/customer/': typeof AuthenticatedCustomerIndexRoute
  '/worker/': typeof AuthenticatedWorkerIndexRoute
  '/customer/request/$id': typeof AuthenticatedCustomerRequestIdRoute
  '/worker/job/$id': typeof AuthenticatedWorkerJobIdRoute
  '/api/public/connect/onboarding': typeof ApiPublicConnectOnboardingRoute
  '/api/public/hooks/auto-cancel-overdue': typeof ApiPublicHooksAutoCancelOverdueRoute
  '/api/public/hooks/auto-confirm-completion': typeof ApiPublicHooksAutoConfirmCompletionRoute
  '/api/public/hooks/auto-force-complete-abandoned': typeof ApiPublicHooksAutoForceCompleteAbandonedRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
  '/api/public/hooks/test-cleanup': typeof ApiPublicHooksTestCleanupRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/troubles': typeof AuthenticatedAdminTroublesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/customer': typeof AuthenticatedCustomerIndexRoute
  '/worker': typeof AuthenticatedWorkerIndexRoute
  '/customer/request/$id': typeof AuthenticatedCustomerRequestIdRoute
  '/worker/job/$id': typeof AuthenticatedWorkerJobIdRoute
  '/api/public/connect/onboarding': typeof ApiPublicConnectOnboardingRoute
  '/api/public/hooks/auto-cancel-overdue': typeof ApiPublicHooksAutoCancelOverdueRoute
  '/api/public/hooks/auto-confirm-completion': typeof ApiPublicHooksAutoConfirmCompletionRoute
  '/api/public/hooks/auto-force-complete-abandoned': typeof ApiPublicHooksAutoForceCompleteAbandonedRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
  '/api/public/hooks/test-cleanup': typeof ApiPublicHooksTestCleanupRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth_/forgot': typeof AuthForgotRoute
  '/auth_/reset': typeof AuthResetRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/troubles': typeof AuthenticatedAdminTroublesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/customer/': typeof AuthenticatedCustomerIndexRoute
  '/_authenticated/worker/': typeof AuthenticatedWorkerIndexRoute
  '/_authenticated/customer/request/$id': typeof AuthenticatedCustomerRequestIdRoute
  '/_authenticated/worker/job/$id': typeof AuthenticatedWorkerJobIdRoute
  '/api/public/connect/onboarding': typeof ApiPublicConnectOnboardingRoute
  '/api/public/hooks/auto-cancel-overdue': typeof ApiPublicHooksAutoCancelOverdueRoute
  '/api/public/hooks/auto-confirm-completion': typeof ApiPublicHooksAutoConfirmCompletionRoute
  '/api/public/hooks/auto-force-complete-abandoned': typeof ApiPublicHooksAutoForceCompleteAbandonedRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
  '/api/public/hooks/test-cleanup': typeof ApiPublicHooksTestCleanupRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/auth/forgot'
    | '/auth/reset'
    | '/admin/audit'
    | '/admin/troubles'
    | '/admin/'
    | '/customer/'
    | '/worker/'
    | '/customer/request/$id'
    | '/worker/job/$id'
    | '/api/public/connect/onboarding'
    | '/api/public/hooks/auto-cancel-overdue'
    | '/api/public/hooks/auto-confirm-completion'
    | '/api/public/hooks/auto-force-complete-abandoned'
    | '/api/public/hooks/push-dispatch'
    | '/api/public/hooks/test-cleanup'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/auth/forgot'
    | '/auth/reset'
    | '/admin/audit'
    | '/admin/troubles'
    | '/admin'
    | '/customer'
    | '/worker'
    | '/customer/request/$id'
    | '/worker/job/$id'
    | '/api/public/connect/onboarding'
    | '/api/public/hooks/auto-cancel-overdue'
    | '/api/public/hooks/auto-confirm-completion'
    | '/api/public/hooks/auto-force-complete-abandoned'
    | '/api/public/hooks/push-dispatch'
    | '/api/public/hooks/test-cleanup'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/auth_/forgot'
    | '/auth_/reset'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/troubles'
    | '/_authenticated/admin/'
    | '/_authenticated/customer/'
    | '/_authenticated/worker/'
    | '/_authenticated/customer/request/$id'
    | '/_authenticated/worker/job/$id'
    | '/api/public/connect/onboarding'
    | '/api/public/hooks/auto-cancel-overdue'
    | '/api/public/hooks/auto-confirm-completion'
    | '/api/public/hooks/auto-force-complete-abandoned'
    | '/api/public/hooks/push-dispatch'
    | '/api/public/hooks/test-cleanup'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthResetRoute: typeof AuthResetRoute
  ApiPublicConnectOnboardingRoute: typeof ApiPublicConnectOnboardingRoute
  ApiPublicHooksAutoCancelOverdueRoute: typeof ApiPublicHooksAutoCancelOverdueRoute
  ApiPublicHooksAutoConfirmCompletionRoute: typeof ApiPublicHooksAutoConfirmCompletionRoute
  ApiPublicHooksAutoForceCompleteAbandonedRoute: typeof ApiPublicHooksAutoForceCompleteAbandonedRoute
  ApiPublicHooksPushDispatchRoute: typeof ApiPublicHooksPushDispatchRoute
  ApiPublicHooksTestCleanupRoute: typeof ApiPublicHooksTestCleanupRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/reset': {
      id: '/auth_/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/forgot': {
      id: '/auth_/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/': {
      id: '/_authenticated/worker/'
      path: '/worker'
      fullPath: '/worker/'
      preLoaderRoute: typeof AuthenticatedWorkerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer/': {
      id: '/_authenticated/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof AuthenticatedCustomerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/troubles': {
      id: '/_authenticated/admin/troubles'
      path: '/admin/troubles'
      fullPath: '/admin/troubles'
      preLoaderRoute: typeof AuthenticatedAdminTroublesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/test-cleanup': {
      id: '/api/public/hooks/test-cleanup'
      path: '/api/public/hooks/test-cleanup'
      fullPath: '/api/public/hooks/test-cleanup'
      preLoaderRoute: typeof ApiPublicHooksTestCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/push-dispatch': {
      id: '/api/public/hooks/push-dispatch'
      path: '/api/public/hooks/push-dispatch'
      fullPath: '/api/public/hooks/push-dispatch'
      preLoaderRoute: typeof ApiPublicHooksPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-force-complete-abandoned': {
      id: '/api/public/hooks/auto-force-complete-abandoned'
      path: '/api/public/hooks/auto-force-complete-abandoned'
      fullPath: '/api/public/hooks/auto-force-complete-abandoned'
      preLoaderRoute: typeof ApiPublicHooksAutoForceCompleteAbandonedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-confirm-completion': {
      id: '/api/public/hooks/auto-confirm-completion'
      path: '/api/public/hooks/auto-confirm-completion'
      fullPath: '/api/public/hooks/auto-confirm-completion'
      preLoaderRoute: typeof ApiPublicHooksAutoConfirmCompletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-cancel-overdue': {
      id: '/api/public/hooks/auto-cancel-overdue'
      path: '/api/public/hooks/auto-cancel-overdue'
      fullPath: '/api/public/hooks/auto-cancel-overdue'
      preLoaderRoute: typeof ApiPublicHooksAutoCancelOverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connect/onboarding': {
      id: '/api/public/connect/onboarding'
      path: '/api/public/connect/onboarding'
      fullPath: '/api/public/connect/onboarding'
      preLoaderRoute: typeof ApiPublicConnectOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/worker/job/$id': {
      id: '/_authenticated/worker/job/$id'
      path: '/worker/job/$id'
      fullPath: '/worker/job/$id'
      preLoaderRoute: typeof AuthenticatedWorkerJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer/request/$id': {
      id: '/_authenticated/customer/request/$id'
      path: '/customer/request/$id'
      fullPath: '/customer/request/$id'
      preLoaderRoute: typeof AuthenticatedCustomerRequestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminTroublesRoute: typeof AuthenticatedAdminTroublesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCustomerIndexRoute: typeof AuthenticatedCustomerIndexRoute
  AuthenticatedWorkerIndexRoute: typeof AuthenticatedWorkerIndexRoute
  AuthenticatedCustomerRequestIdRoute: typeof AuthenticatedCustomerRequestIdRoute
  AuthenticatedWorkerJobIdRoute: typeof AuthenticatedWorkerJobIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminTroublesRoute: AuthenticatedAdminTroublesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCustomerIndexRoute: AuthenticatedCustomerIndexRoute,
  AuthenticatedWorkerIndexRoute: AuthenticatedWorkerIndexRoute,
  AuthenticatedCustomerRequestIdRoute: AuthenticatedCustomerRequestIdRoute,
  AuthenticatedWorkerJobIdRoute: AuthenticatedWorkerJobIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthResetRoute: AuthResetRoute,
  ApiPublicConnectOnboardingRoute: ApiPublicConnectOnboardingRoute,
  ApiPublicHooksAutoCancelOverdueRoute: ApiPublicHooksAutoCancelOverdueRoute,
  ApiPublicHooksAutoConfirmCompletionRoute:
    ApiPublicHooksAutoConfirmCompletionRoute,
  ApiPublicHooksAutoForceCompleteAbandonedRoute:
    ApiPublicHooksAutoForceCompleteAbandonedRoute,
  ApiPublicHooksPushDispatchRoute: ApiPublicHooksPushDispatchRoute,
  ApiPublicHooksTestCleanupRoute: ApiPublicHooksTestCleanupRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
